name: Android Debug Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Required to calculate version from git history

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew assembleDebug

    - name: Rename APK
      id: rename_apk
      run: |
        VERSION=$(git rev-list --count HEAD)
        REVNO=$(git rev-parse HEAD | cut -c1-8)
        NAME=${GITHUB_REPOSITORY#*/}
        APK_PATH=$(find build/outputs/apk/debug -name "*-debug.apk" | head -n 1)
        DEBUG_APK_NAME=${NAME}-${VERSION}-${REVNO}-debug.apk
        mv "$APK_PATH" "build/outputs/apk/debug/$DEBUG_APK_NAME"
        echo "new_path=build/outputs/apk/debug/$DEBUG_APK_NAME" >> $GITHUB_OUTPUT
        echo "new_name=$DEBUG_APK_NAME" >> $GITHUB_OUTPUT

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: pddroidparty-debug-apk
        path: ${{ steps.rename_apk.outputs.new_path }}
